// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/budget component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("budget")
	ScopeName = "github.com/paulojmdias/otel-budget-components/processor/budgetprocessor"
)

const (
	LogsStability    = component.StabilityLevelDevelopment
	TracesStability  = component.StabilityLevelDevelopment
	MetricsStability = component.StabilityLevelDevelopment
)
