// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/budget component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("budget")
	ScopeName = "github.com/paulojmdias/otel-budget-processor/extension/budgetextension"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
