// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/paulojmdias/otel-budget-processor/extension/budgetextension")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/paulojmdias/otel-budget-processor/extension/budgetextension")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter              metric.Meter
	mu                 sync.Mutex
	registrations      []metric.Registration
	BudgetBurnRate     metric.Float64Gauge
	BudgetDroppedItems metric.Int64Counter
	BudgetExempt       metric.Int64Gauge
	BudgetFleetSpend   metric.Int64Gauge
	BudgetKeyOverflows metric.Int64Counter
	BudgetKeys         metric.Int64Gauge
	BudgetLimit        metric.Int64Gauge
	BudgetOfferedSize  metric.Int64Counter
	BudgetSpend        metric.Int64Counter
	BudgetSyncAge      metric.Float64Gauge
	BudgetSyncErrors   metric.Int64Counter
	BudgetTier         metric.Int64Gauge
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.BudgetBurnRate, err = builder.meter.Float64Gauge(
		"otelcol_budget_burn_rate",
		metric.WithDescription("Burn rate per window, 1.0 is the sustainable pace. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BudgetDroppedItems, err = builder.meter.Int64Counter(
		"otelcol_budget_dropped_items",
		metric.WithDescription("Items (log records, spans, data points) dropped by the budget processor. [Development]"),
		metric.WithUnit("{item}"),
	)
	errs = errors.Join(errs, err)
	builder.BudgetExempt, err = builder.meter.Int64Gauge(
		"otelcol_budget_exempt",
		metric.WithDescription("1 when the key is listed in exempt (accounted, never enforced). [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.BudgetFleetSpend, err = builder.meter.Int64Gauge(
		"otelcol_budget_fleet_spend",
		metric.WithDescription("Period to date spend of the whole fleet as seen by this replica, in micro units of the configured currency. Equal on every replica once synced. [Development]"),
		metric.WithUnit("{microcurrency}"),
	)
	errs = errors.Join(errs, err)
	builder.BudgetKeyOverflows, err = builder.meter.Int64Counter(
		"otelcol_budget_key_overflows",
		metric.WithDescription("Resources folded into __other__ because max_keys was reached. [Development]"),
		metric.WithUnit("{resource}"),
	)
	errs = errors.Join(errs, err)
	builder.BudgetKeys, err = builder.meter.Int64Gauge(
		"otelcol_budget_keys",
		metric.WithDescription("Distinct budget keys seen this period. [Development]"),
		metric.WithUnit("{key}"),
	)
	errs = errors.Join(errs, err)
	builder.BudgetLimit, err = builder.meter.Int64Gauge(
		"otelcol_budget_limit",
		metric.WithDescription("Period budget in micro units of the configured currency. [Development]"),
		metric.WithUnit("{microcurrency}"),
	)
	errs = errors.Join(errs, err)
	builder.BudgetOfferedSize, err = builder.meter.Int64Counter(
		"otelcol_budget_offered_size",
		metric.WithDescription("Bytes offered to the budget processor before enforcement. [Development]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.BudgetSpend, err = builder.meter.Int64Counter(
		"otelcol_budget_spend",
		metric.WithDescription("Accounted spend in micro units of the configured currency. [Development]"),
		metric.WithUnit("{microcurrency}"),
	)
	errs = errors.Join(errs, err)
	builder.BudgetSyncAge, err = builder.meter.Float64Gauge(
		"otelcol_budget_sync_age",
		metric.WithDescription("Age of the fleet totals used for decisions. [Development]"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	builder.BudgetSyncErrors, err = builder.meter.Int64Counter(
		"otelcol_budget_sync_errors",
		metric.WithDescription("Sync errors by mode and operation. [Development]"),
		metric.WithUnit("{error}"),
	)
	errs = errors.Join(errs, err)
	builder.BudgetTier, err = builder.meter.Int64Gauge(
		"otelcol_budget_tier",
		metric.WithDescription("Current enforcement tier. [Development]"),
		metric.WithUnit("{tier}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
